development:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Feel free to change this message in <em>config/environments/development.rb</em>"
  bookqueue_logo:   "http://flexcode-apps.s3.amazonaws.com/bookqueue/logo.gif"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"

test:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Feel free to change this message in <em>config/environments/temp.rb</em>"
  bookqueue_logo:   "http://flexcode-apps.s3.amazonaws.com/bookqueue/logo.gif"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"
    
production:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Feel free to change this message in <em>config/environments/production.rb</em>"
  bookqueue_logo:   "http://flexcode-apps.s3.amazonaws.com/bookqueue/logo.gif"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"

