# bookqueue config variables

# site_url          - your website address. Please include http://
# site_owner        - your name. will appear in feed items and tweets
# site_title        - a catchphrase for your website header
# send_twitter      - set this to yes to enable twitter notification (yes / no)
# 
# DO NOT FORGET TO SET YOUR TWITTER ACCOUNT in /config/twitter.yml

development:
  site_url: http://lolxenuqueue.com/
  site_owner: xenu
  site_title: Welcome to xenu's bookqueue. Feel free to change this message in <em>config.yml</em>
  send_twitter: yes
  
test:
  site_url: http://lolxenuqueue.com/  
  site_owner: xenu
  site_title: Welcome to xenu's bookqueue. Feel free to change this in <em>config.yml</em>
  send_twitter: no

production:
  site_url: http://lolxenuqueue.com/
  site_owner: xenu
  site_title: Welcome to xenu's bookqueue. Feel free to change this in <em>config.yml</em>  
  send_twitter: yes