development:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Change this message in <em>config/environments/development.rb</em>"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"

test:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Change this message in <em>config/environments/temp.rb</em>"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"
    
production:
  bookqueue_url:    "http://lolxenuqueue.com/"
  bookqueue_title:  "Welcome to xenu's bookqueue. Change this message in <em>config/environments/production.rb</em>"

  owner_name:        "xenu"
  owner_email:       "xenu@xenucorp.com"

  twitter_use:      false
  twitter_login:    "xenuqueue"
  twitter_password: "xenu21"

